server:
  port: 8080

spring:
  application:
    name: linkpulse

  datasource:
    url: jdbc:mysql://localhost:3306/linkpulse?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Shanghai&characterEncoding=utf8
    username: linkpulse_user
    password: xuqi123456789

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: false

  data:
    redis:
      host: localhost
      port: 6379

jwt:
  secret: linkpulse-super-secret-key-must-be-at-least-32-bytes
  expiration: 86400000
rocketmq:
  name-server: 127.0.0.1:9876
  producer:
    group: linkpulse-access-event-producer