server:
  port: 8080

spring:
  application:
    name: linkpulse

  datasource:
    driver-class-name: org.apache.shardingsphere.driver.ShardingSphereDriver
    url: jdbc:shardingsphere:classpath:sharding.yaml

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    open-in-view: false

  data:
    redis:
      host: localhost
      port: 6379

jwt:
  secret: linkpulse-super-secret-key-must-be-at-least-32-bytes
  expiration: 86400000

rocketmq:
  name-server: 127.0.0.1:9876
  producer:
    group: linkpulse-access-event-producer
springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: method
    tags-sorter: alpha